global using LazyMagic.Client.Base;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using BlazorUI;
global using System.Reactive.Linq;
global using LazyMagic.Blazor;
global using Microsoft.JSInterop;
global using Newtonsoft.Json.Linq;
global using ViewModels;